modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${license}"
logoBlur=false
issueTrackerURL="${issue_tracker}"
logoFile="${mod_id}_icon.png"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/wendall911/ChargedCharms/${mod_update_branch}/files/updates.json"
    authors="${mod_author}"
    description='''
    ${mod_description}
    '''
[[dependencies.chargedcharms]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.chargedcharms]]
    modId="minecraft"
    mandatory=true
    versionRange="${forge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.chargedcharms]]
    modId="curios"
    mandatory=true
    versionRange="${curios_version_range}"
    ordering="NONE"
    side="BOTH"
