# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=2.1.1.0
last_mod_version=2.1.0.0
group=com.github.wendall911.chargedcharms

# Common
minecraft_version=26.1.2
mixin_extras_version=0.5.3
whitenoise_version=2.1.1
whitenoise_range=[2.1.1,3.0.0)
fabric_whitenoise_range=[">=2.1.1","<=3.0.0"]
mixin_version=0.8.5
java_version=25

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.11-beta
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[26.1, 26.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.146.0+26.1.2
fabric_api_min_version=>=0.143.10
fabric_loader_version=0.19.1
fabric_loader_min_version=>=0.15
fabric_mc_version_range=[">26.1-"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=18.0.0-alpha.8
# https://www.curseforge.com/minecraft/mc-mods/cardinal-components-api/files/all
cardinal_components_version=8.0.0

# Curios / Trinkets
# https://maven.theillusivec4.top/top/theillusivec4/curios/curios-neoforge/
curios_version=15.0.0-beta.2
curios_version_range=[5.2.0,)
# https://maven.nucleoid.xyz/#/releases/eu/pb4/trinkets
trinkets_version=4.0.0-alpha.7+26.1

# Integration and Testing Mods
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version=29.5.0.26
jei_minecraft_version=26.1.2
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/all
rei_version=21.11.814
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all
architectury_version=19.0.1
# https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/all
cloth_config_version=26.1.154
sodium_fabric_version=???
sodium_neoforge_version=???
# https://maven.gegy.dev/#/releases/dev/lambdaurora/lambdynamiclights/lambdynamiclights-api
dynamiclights_version=4.10.1+26.1.1
# https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights/files/all
dynamiclights_neoforge_version=7892203
ars_nouveau_version=???
terrablender_neoforge_version=???
geckolib_neoforge_version=???
lucent_version=???

# Mod options
mod_display_name=Charged Charms
mod_id=chargedcharms
mod_name=ChargedCharms
mod_author=wendall911
mod_credits=Knoface
license=LGPL-3.0-or-later
mod_description=Adds several 'Charged' charms that are designed to have a set number of charges for the given effect.
mod_update_branch=1.21

# CurseForge/Modrinth Options
# Global properties are located in ~/.gradle/gradle.properties
# DO NOT put private keys here
curseforge_api_key_prop=ccCurseApiKey
curseforge_id=682683
curseforge_slug=charged-charms
modrinth_api_key_prop=modrinthKey
modrinth_id=cqzqfZKX
discord_webhook_prop=ccDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=26.1,26.1.1,26.1.2
