# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
mod_version=2.1.0.0
last_mod_version=2.0.1.0

# Common
minecraft_version=1.18.2
minecraft_short_version=1.18
java_version=17
whitenoise_version=1.18.2.4
whitenoise_range=[1.18.2, 1.18.3)

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2022.11.06

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=40.3.11
forge_version_range=[40,)
forge_mc_version_range=[1.18.2,1.18.3)

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.77.0+1.18.2
fabric_mc_version_range=1.18.2
fabric_loader_version=0.17.2
fabric_loader_min_version=>=0.14
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=3.2.5
# https://www.curseforge.com/minecraft/mc-mods/cardinal-components-api/files/all
cardinal_components_version=4.2.0

# Curios
curios_version=5.0.9.1
curios_version_range=[1.18-5.0.0.0,)
trinkets_version=3.3.1

# Other mods
jei_version=10.2.1.1009
rei_version=8.4.778
architectury_version=5137927
architectury_forge_version=5137931
mantle_version=1.9.54
tic_version=3.7.2.167

# Mod options
mod_id=chargedcharms
mod_name=Charged Charms
mod_author=wendall911, Knoface
license=LGPL-3.0-or-later
issue_tracker=https://github.com/wendall911/chargedcharms/issues
mod_description=Adds several 'Charged' charms that are designed to have a set number of charges for the given effect.
mod_update_branch=1.18.2

# CurseForge/Modrinth Options
release_type=release
release_versions=1.18.2
