# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=2.2.1.0
last_mod_version=2.2.0.2

# Common
minecraft_version=1.21.10
mixin_extras_version=0.3.5
whitenoise_version=2.0.5
whitenoise_range=[2.0.0,3.0.0)
fabric_whitenoise_range=[">=2.0.0","<=3.0.0"]
mixin_version=0.8.5
java_version=21
accessories_version=1.4.0-beta
accessories_version_range=[1.4.0,)

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2025.10.05
mappings_minecraft_version=1.21.9

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.10.20-beta
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[1.21.9, 1.21.11)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.10-20251010.172816

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.136.0+1.21.10
fabric_loader_version=0.17.3
fabric_loader_min_version=>=0.15
fabric_mc_version_range=[">=1.21.9","<=1.21.11"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=16.0.0-rc.1
# https://www.curseforge.com/minecraft/mc-mods/cardinal-components-api/files/all
cardinal_components_version=7.2.0

# Integration and Testing Mods
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version=26.0.0.1
jei_minecraft_version=1.21.10
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/all
rei_version=20.0.811
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all
architectury_version=18.0.5
# https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/all
cloth_config_version=20.0.148
sodium_fabric_version=7088176
sodium_neoforge_version=???
# https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights/files/all
dynamiclights_version=4.8.5
dynamiclights_neoforge_version=7117980
ars_nouveau_version=???
terrablender_neoforge_version=7098524
geckolib_neoforge_version=5.3-alpha-1
lucent_version=???

# Mod options
mod_display_name=Charged Charms
mod_id=chargedcharms
mod_name=ChargedCharms
mod_author=wendall911
mod_credits=Knoface
license=LGPL-3.0-or-later
mod_description=Adds several 'Charged' charms that are designed to have a set number of charges for the given effect.
mod_update_branch=1.21

# CurseForge/Modrinth Options
curseforge_api_key_prop=ccCurseApiKey
curseforge_id=682683
curseforge_slug=charged-charms
modrinth_api_key_prop=modrinthKey
modrinth_id=cqzqfZKX
discord_webhook_prop=ccDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=1.21.9,1.21.10
