#!/bin/bash

rm Forge/build/libs/*
rm Fabric/build/libs/*
./gradlew :Forge:build || exit 1
./gradlew :Fabric:build || exit 1
cp Forge/build/libs/*FORGE.jar ~/tmp/cc_test/
cp Fabric/build/libs/*FABRIC.jar ~/tmp/cc_test/
